name: projects
description: "StepNote - Flashcard Trainer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.0
  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  fl_chart: ^1.1.1
  path_provider: ^2.1.5
  easy_video_editor: ^0.1.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  app_links: ^6.4.1
  firebase_storage: ^13.0.3
  http: ^1.5.0
  get_it: ^7.2.0
  intl: ^0.20.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/sample.mp4
